{% set name = "jaraco.classes" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 24ec75e16d91bbae0fe89312c5cbbe4b2407d40629dc80463653d23868965c5c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm >=1.15.0
  run:
    - python >=3.6
    - more-itertools

test:
  imports:
    - jaraco
    - jaraco.classes

about:
  home: https://github.com/jaraco/jaraco.classes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: jaraco.classes
  dev_url: https://github.com/jaraco/jaraco.classes

extra:
  recipe-maintainers:
    - pmlandwehr
    - carlodri
