{% set name = "jaraco.classes" %}
{% set version = "3.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6745f113b0b588239ceb49532aa09c3ebb947433ce311ef2f8e3ad64ebb74594

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm >=3.4.1
  run:
    - python >=3.7
    - more-itertools

test:
  imports:
    - jaraco
    - jaraco.classes

about:
  home: https://github.com/jaraco/jaraco.classes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: jaraco.classes
  dev_url: https://github.com/jaraco/jaraco.classes

extra:
  recipe-maintainers:
    - carlodri
