travis:
  secure:
    BINSTAR_TOKEN: RHsa76r98SIqaPS6k4UDQ9AphG+S3t1T4EvfFWxcTBoAjUY7GfycmWcWULGolqe1W+7ZfhlAea+tysNgZEPat8xfFO7xCOIpKTBri1gdcx0XdJo8XVX3/oXP82ZFLHMB645kJuVIBIFZZuMczWhX1LClhM3v8dKfMCN4Xr23Vg6wuR82LXlHKVkF2wtOb6LZbctFqKFIBsBVVu8quh/A2N7xFz721CTKwy0OCQ0ON0hDvuZOnSgc/2iRfZE5I5yo0rgjAl7FgsXq9UpclON5kVhKptyzAv8s7s1y6iPmQlvllcJywtOJIRYIwKxlihNzl09FzZANeobtMsO5nOklRWTcNvMJYuTKk9sPLqqGvKgcaQTe0zukFLpcGzpOBsaB2XKRMPluZDAWaTITpcinICjSiZUnE1TAO5F1mQ3uooRb8WKPbwf0+Uvgo15N8SKYvTqqfytEmCAiZghgjL1DZSwJgstxAJJPyaQw4KOOv2GCVZ008WGR0v5fzQ6KBMiAmwf96OixLmTBZpHQFHR9O5WjLHlz14PrcTJPj3ZG+pwwCe5oF7o/KfAEiBvhoIPqioO5PMcCaD2CvbNLglCqVxvUbrk6uNB+XtGUbS5Gf7Y5s9JxVUStLb45OSQbUgWwCuKkkPWMnowHy3PQ5TVf8pIQkY51mnNFG2Exah5llE4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
